### ISSUE TITLE
Poor relay performance in EU

### ISSUE THREAD

**Issue by Eos109** [vgskye/e4mc-minecraft-architectury#30] opened 2024-07-29 17:49 UTC
Am hosting a heavily modded world from mid EU, one friend tries to connect from eastern EU and can barely play, in his words "If I see a Zombie, I'm already dead", and another tries to connect from the USA and just times out, doesn't even get to connect, cant bring you error logs since on my side everything is fine, lag doesn't throw error logs, and time out, well is a time out

**Comment by bubzilla** [comment] 2024-08-16 22:41
likely your internet lmao

**Comment by vgskye** [comment] 2024-09-17 05:39
duplicate of #19

**Closed as not planned by vgskye** 2024-09-17 05:39 UTC
