### ISSUE TITLE
"An error has occurred with e4mc"

### ISSUE THREAD

**Issue by Flowcheer** [vgskye/e4mc-minecraft-architectury#59] opened 2024-10-29 22:54 UTC
Whenever i try opening the server it just throws me that message, in this case i downgraded to 5.2.0 because i thought it would fix it but nothing
logs: https://paste.ee/p/CgedE

**Comment by Flowcheer** [comment] 2024-10-29 23:01
I saw issue #28 and tried seeing if i could reach the best relay website, it gives this but the game still doesnt work?
![image](https://github.com/user-attachments/assets/58b28d1e-2f07-45a2-8391-f0b1de14706f)

**Comment by Flowcheer** [comment] 2024-11-13 19:52
I tried using the mod in Windows and it works just fine. Maybe theres a library you have to install before using it?

**Comment by vgskye** [comment] 2024-11-18 05:17
probably a duplicate of #19, seeing as it's seemingly intermittent?

**Closed as not planned by vgskye** 2024-11-18 05:17 UTC

**Comment by Flowcheer** [comment] 2024-11-18 17:55
I wouldnt say so, the mod can fetch the relay but the Quiclime session throws an error when trying to connect to the relay

**Comment by Flowcheer** [comment] 2024-11-18 17:57
Im suspecting its some missing library because i tried using the mod on Windows and it connects to the relays and works fine
