### ISSUE TITLE
players disconnected right after joining

### ISSUE THREAD

**Issue by shellnutlives** [vgskye/e4mc-minecraft-architectury#62] opened 2024-11-18 04:35 UTC
hosting a modded world and players are disconnected a few seconds after joining. the world is rendered for players and inventory occasionally appears, but players are disconnected after a few seconds. using multimc, logs are included

https://mclo.gs/oizpGaU

**Comment by vgskye** [comment] 2024-11-18 05:11
duplicate of #19

**Closed as not planned by vgskye** 2024-11-18 05:11 UTC
