### ISSUE TITLE
Unplayable lag out of nowhere

### ISSUE THREAD

**Issue by gregest** [vgskye/e4mc-minecraft-architectury#39] opened 2024-08-14 12:35 UTC
Me and my friend are playing chocolate edition, yesterday (2024 / 08 / 13) and before that, everything was working perfectly fine but today (2024 / 08 / 14) it became completely unplayable.   

The player joining is always stuck in place and unable to do anything, you can see the other person moving and doing stuff and they are playing the game, but the player joining cannot do anything. If the frozen player manages to break a block, the block stays broken and nothing drops of course, but for the "host's side" it properly breaks and drops and updates

We tried either of us opening to lan but it didn't change anything worked. We thought that opening to lan with cheats might have been causing it, but opening without it changed nothing the same way.

The modpack haven't had an update, we haven't added any extra mods and nothing changed.  

 
[latest.log](https://github.com/user-attachments/files/16613018/latest.log)

**Comment by vgskye** [comment] 2024-08-18 03:08
gonna tag as duplicate of #30

**Closed as not planned by vgskye** 2024-08-18 03:08 UTC
