### ISSUE TITLE
e4mc timeout issue with anyone connecting

### ISSUE THREAD

**Issue by Twiigtv** [vgskye/e4mc-minecraft-architectury#40] opened 2024-08-22 15:18 UTC
https://mclo.gs/G9UqGPl

logs first

Using modpack BigChadGuysPlus non Cobblemon through the Prism Launcher but using Curseforge to host.

Small group of friends have been using this modpack for roughly 3 weeks now with no issue, then suddenly nobody could join and would get timed out. 

We have tried updating the modpack, reinstalling the modpack, looking for alternate versions of e4mc and fabric-language-kotlin, but nothing works.

The attached logs are from today, with a fresh install of the modpack.

Players join, fall through the world for 10 seconds, then are kicked.

Any help appreciated!

**Comment by Alpacacopter** [comment] 2024-08-22 22:10
having same issue but not even using a modpack
logs:
my friends
https://mclo.gs/gjhwMfL
mine
https://mclo.gs/VXVaULQ

**Comment by vgskye** [comment] 2024-09-17 05:42
duplicate of #19, it seems

**Closed as not planned by vgskye** 2024-09-17 05:42 UTC
