### ISSUE TITLE
Fabric. 1.20.4 friends can't connect

### ISSUE THREAD

**Issue by Official-V-Zer0** [vgskye/e4mc-minecraft-architectury#16] opened 2024-07-07 18:01 UTC
They get the error (when doing link:port): Connection timed out: getsockopt

also when we just did the ip link we got a long error
![image](https://github.com/vgskye/e4mc-minecraft-architectury/assets/154614813/46b32860-8372-4ffb-bffc-819664a8ab58)

**Comment by shvedes** [comment] 2024-07-12 13:36
Do not use port, paste only em4c ip into input bar

**Comment by vgskye** [comment] 2024-07-13 03:39
mm, sounds like one of your mods are acting weird, try with just e4mc?

**Comment by Official-V-Zer0** [comment] 2024-07-13 18:32
> Do not use port, paste only em4c ip into input bar

Didn't work either as seen by the screenshot under

**Comment by Official-V-Zer0** [comment] 2024-07-13 18:33
> mm, sounds like one of your mods are acting weird, try with just e4mc?

Would kinda defeat the purpose of the modpack and the work we're currently doing on something invoving the modpack

**Comment by shvedes** [comment] 2024-07-14 13:23
> > Do not use port, paste only em4c ip into input bar
> 
> Didn't work either as seen by the screenshot under

I don't want to offend the maintainer in any way, but try [this](https://modrinth.com/mod/mcwifipnp) mod. If it works with this mod, then you know where the problem is.

I say this because e4mc did not work for me either, and I was only able to share ip with the mod that I indicated above

**Comment by Official-V-Zer0** [comment] 2024-07-14 13:41
> > > Do not use port, paste only em4c ip into input bar
> > 
> > 
> > Didn't work either as seen by the screenshot under
> 
> I don't want to offend the maintainer in any way, but try [this](https://modrinth.com/mod/mcwifipnp) mod. If it works with this mod, then you know where the problem is.
> 
> I say this because e4mc did not work for me either, and I was only able to share ip with the mod that I indicated above

Will try it once I get the modpack up and running again, ran into unexpected issues suddenly

**Comment by vgskye** [comment] 2024-07-14 19:09
> > mm, sounds like one of your mods are acting weird, try with just e4mc?
> 
> Would kinda defeat the purpose of the modpack and the work we're currently doing on something invoving the modpack

...I mean, what am I supposed to do, fix some other mod I have no relation to? if it works fine with just e4mc, it's not an e4mc issue

**Comment by vgskye** [comment] 2024-07-14 19:13
closing for now, reopen if issue persists with just e4mc

**Closed as not planned** 2024-07-14 19:13 UTC

**Comment by Official-V-Zer0** [comment] 2024-07-14 19:44
I'm not asking you to fix anything, I'm asking if anyone at all knows anything about what is breaking
