### ISSUE TITLE
An error occured in e4mc

### ISSUE THREAD

**Issue by visquint** [vgskye/e4mc-minecraft-architectury#46] opened 2024-09-09 20:03 UTC
the mod prints a vague error whenever someone tries to connect to the world
my modlist and the errors are in the log attached below
https://mclo.gs/KP6p3Mm

**Comment by bradcarnage** [comment] 2024-09-16 19:03
i assume this is due to server hosting being shut down for e4mc. i will try to contact the mod author to see if they need hosting in the meantime

**Comment by vgskye** [comment] 2024-09-17 05:36
@bradcarnage you are incorrect. eu and us relays get overloaded at times but it is never outright shut down.
duplicate of #19

**Closed as not planned by vgskye** 2024-09-17 05:36 UTC
