### ISSUE TITLE
Timed Out error

### ISSUE THREAD

**Issue by AmaranthMoth** [vgskye/e4mc-minecraft-architectury#45] opened 2024-09-09 17:24 UTC
Hello!!! I am officially going insane. Usually I'm not one to rely on websites to ask for help but I can promise that I have no idea how to fix this. Me and my friend managed to play together one singular time before everything came crashing down. We use EU servers, I have completely disabled my entire firewall in an attempt to get this to work, I must have looked at the log about a million times. When My friend tries to connect, they ALWAYS time out. I have even edited the value of when the time out should happen and it still doesn't function. I have genuinely no idea of what to do. We are playing with a slightly edited version of BigChadGuys Plus which removes some of the mods that were included in the original modpack. If anyone has a shred of an idea of why this might be happening please enlighten me. My friend in in US so we have a decent distance between us but I doubt that's a factor.

**Comment by AmaranthMoth** [comment] 2024-09-09 17:25
if any other information is needed please contact me im genuinely so distraught I've been troubleshooting this for 3 days

**Comment by vgskye** [comment] 2024-09-17 05:39
duplicate of #19

**Closed as not planned by vgskye** 2024-09-17 05:39 UTC
