### ISSUE TITLE
Issues with loading a modded world

### ISSUE THREAD

**Issue by irmilla2006** [vgskye/e4mc-minecraft-architectury#29] opened 2024-07-23 21:40 UTC
I'm trying to use this mod to run a modded world with a friend of mine, but whenever she tries to join she just stands still on my screen until eventually she disconnects. Is there anything that can be done to fix this or is it something more to do with her/my hardware?

**Comment by vgskye** [comment] 2024-07-27 06:35
logs?

**Comment by OxYmPo** [comment] 2024-08-26 21:17
I have the same error, the servers slow down and sometimes my friends disconnect from the game after they join the game.

**Comment by vgskye** [comment] 2024-09-17 05:41
duplicate of #19, I presume

**Closed as not planned by vgskye** 2024-09-17 05:41 UTC
