### ISSUE TITLE
After joining, doesn't load map and disconnects after 20s.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [vgskye/e4mc-minecraft-architectury#54] opened 2024-10-19 21:42 UTC
#### **Screencast**

> https://github.com/user-attachments/assets/05bf6001-9203-47a5-b796-96685a930ebe

#### **Screenshots**

1.	> ![image](https://github.com/user-attachments/assets/b5f1c3af-1ce0-40da-a53b-313a3cc652d7)
1.	> ![image](https://github.com/user-attachments/assets/31b2ceba-e545-4ba7-a8d5-fcfc6e98167a)

**Comment by roke-julian-lockhart** [comment] 2024-10-19 21:46
> https://github.com/vgskye/e4mc-minecraft-architectury/issues/54#issue-2599634222

Considering that we're using a mod pack (https://kim.nl.tab.digital/s/rw5oHT3PxjGYQKj) it could be an inter-mod incompatibility, and since Essential https://modrinth.com/mod/essential/version/qRBNWU56 functions, we'll just use that instead.

**Comment by roke-julian-lockhart** [comment] 2024-10-19 21:56
> https://github.com/vgskye/e4mc-minecraft-architectury/issues/54#issuecomment-2424228214

Well, I'll leave it open for triage at least, in case it's reproducible.

**Comment by vgskye** [comment] 2024-10-23 05:10
duplicate of #19.

**Closed as not planned by vgskye** 2024-10-23 05:10 UTC
